### ISSUE TITLE
Modal animation causes page to scroll up

### ISSUE THREAD

**Issue by karnafun** [karnafun/Research-clouds#13]
If you are scrolling down and clicking "edit" on an article, the page scrolls up.
i found  this https://github.com/jschr/bootstrap-modal/issues/131 
there is some code at the button that should solve it. i have no idea what i does yet.

**Comment by ilyakolker** [comment]
@karnafun I tested it on the user-profile page and can not see the bug.

**Comment by karnafun** [comment]
@ilyakolker  you're right.
I have tested it again, it happens only in explorer. chrome is fine.
here is the bug:

this is my screen BEFORE i click edit:

![image](https://user-images.githubusercontent.com/23281437/37732952-345d9590-2d4f-11e8-9784-668163db610f.png)

this is my screen right AFTER I CLICK EDIT:
![image](https://user-images.githubusercontent.com/23281437/37732965-3fb5188c-2d4f-11e8-8c63-22269956a6c6.png)

**Comment by ilyakolker** [comment]
@karnafun  I see that bug, it is only happening on explorer!
Tested it on FireFox as well
Not a priority at this point.
![image](https://user-images.githubusercontent.com/27788059/37735714-8ecd9356-2d57-11e8-8193-f9cdb86e7283.png)

**Comment by karnafun** [comment]
Bug is only for Internet Explorer.
Not giving full support to internet explorer at this point.
Issue closed.
